### PR TITLE
Parameters in Camel Casing

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Regarding the issue #4, I would like to propose to rename all the parameters containing 
> .[a-z]

 by 

> .[A-Z] 

What do you think?

Edit - 02/15/2017: since my issue #4 has been removed/hidden, let me explain here what is my approach around that:
* When we use `New-AzureRmResourceGroupDeployment` with inline parameters like `-sqlserver.login myLogin` we have an error message because of the `.`. I know we could use other alternatives like `-TemplateParameterObject` or `-TemplateParameterFile` like described [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy#parameters), but could be a limitation.
* Furthermore, [best practices for templates parameters](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-template-best-practices#parameters) indicates: 
> 2. Parameter names should follow camelCasing.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
This PR is not done, it's in progress but if you have feedback for me so far, please let me know.

**Comment by mathieu-benoit** [comment]
I'm done. Ready for your review and comments. Thanks!

**Comment by mathieu-benoit** [comment]
I'm done. Ready for your review and comments. Thanks!

**Comment by mathieu-benoit** [comment]
I'm done. Ready for your review and comments. Thanks!

**Comment by mathieu-benoit** [comment]
Hey @sc-dmitrykostenko, any thoughts?

**Comment by sc-dmitrykostenko** [comment]
Hi Mathieu,

I regret to say that our current legal policy does not allow external contributions, which means we can only accept pull requests from Sitecore employees. We are working changing the policy for this repository.

I will also have to remove your commit  e248ebc from the master branch. You may have merge conflicts in your branches once you pull changes from this repository.

My apologies for the inconvenience.

_With best regards,
Dmitry Kostenko
Sitecore_

**Comment by mathieu-benoit** [comment]
Hi @sc-dmitrykostenko, ok got it, thank you for the follow up.
FYI, I'm till documenting on my own fork/clone some fix and improvements: https://alwaysupalwayson.blogspot.com/2017/02/lets-cook-and-play-with-default.html that I'm happy to share with the community ;)

**Comment by mathieu-benoit** [comment]
This PR has been taken into account here in Sitecore 8.2.3 templates: https://github.com/Sitecore/Sitecore-Azure-Quickstart-Templates/commit/f4d1e63c820a5d3a5bfde8e4d6200a10236fb61a. We could close this PR. Thanks!

**Pull request closed without merging**
